export interface TimelinePhase {
  id: string;
  name: string;
  period: string;
  dayRange: string;
  neuroLevel: number; // 0-100 relative to baseline
  description: string;
  symptoms: string[];
  neurotransmitterStatus: {
    dopamine: string;
    serotonin: string;
    gaba: string;
    glutamate: string;
    cortisol: string;
  };
  prioritySupplements: {
    name: string;
    reason: string;
  }[];
  lifestyleActions: string[];
  moodExpectation: string;
  warnings: string[];
}

export const TIMELINE_PHASES: TimelinePhase[] = [
  {
    id: 'baseline',
    name: 'Baseline (Pre-Use)',
    period: 'Before Substance Use',
    dayRange: 'Reference Point',
    neuroLevel: 100,
    description:
      'Before substance use, the brain operates with balanced neurotransmitter levels. Dopamine provides motivation and reward, serotonin regulates mood and sleep, GABA provides calming balance, and glutamate supports learning and memory. The gut-brain axis is intact, the blood-brain barrier is healthy, and mitochondrial energy production is optimal. This is the state the brain is working to return to during recovery.',
    symptoms: ['Normal mood regulation', 'Healthy motivation and reward response', 'Balanced sleep-wake cycle', 'Stable appetite', 'Normal stress response', 'Healthy gut-brain communication'],
    neurotransmitterStatus: {
      dopamine: 'Normal — balanced reward signaling, motivation, and pleasure response',
      serotonin: 'Normal — stable mood, healthy sleep architecture, emotional balance',
      gaba: 'Normal — adequate calming tone, balanced anxiety response',
      glutamate: 'Normal — healthy learning, memory consolidation, balanced excitation',
      cortisol: 'Normal — appropriate stress response, healthy HPA axis function',
    },
    prioritySupplements: [],
    lifestyleActions: [],
    moodExpectation: 'Normal emotional range with natural ups and downs. Motivated, social, and emotionally resilient.',
    warnings: [],
  },
  {
    id: 'active-use',
    name: 'Active Use',
    period: 'During Chronic Use',
    dayRange: 'Variable',
    neuroLevel: 120,
    description:
      'During active substance use, neurotransmitter levels are artificially elevated far above normal baseline. The brain responds by downregulating receptors and reducing natural neurotransmitter production as a homeostatic adaptation. While the user may feel euphoric and energized during use, the neuroadaptation is causing progressive damage: dopamine receptors are being blunted, serotonin transporters are downregulating, the gut barrier is being compromised, and oxidative stress is accumulating. The higher the neurochemical levels during use, the harder the crash during withdrawal.',
    symptoms: [
      'Artificially elevated mood during intoxication',
      'Progressively shorter highs with longer comedowns',
      'Increasing tolerance requiring higher doses',
      'Paranoia and perceptual disturbances',
      'Sleep deprivation and circadian disruption',
      'Nutritional neglect and weight changes',
      'Social isolation and relationship damage',
      'Financial stress and risky behavior',
    ],
    neurotransmitterStatus: {
      dopamine: 'Artificially 5-10x elevated during use; receptors downregulating between uses; natural production shutting down',
      serotonin: 'Artificially elevated (stimulants); progressively depleting reserves; SERT downregulating',
      gaba: 'Suppressed (stimulants) or artificially elevated (depressants); rebound anxiety between uses',
      glutamate: 'Elevated — compensatory upregulation; excitotoxic damage accumulating; receptors becoming hypersensitive',
      cortisol: 'Chronically elevated — chronic stress state; immune suppression; gut barrier degradation',
    },
    prioritySupplements: [],
    lifestyleActions: [],
    moodExpectation: 'Unpredictable swings between euphoria (during use) and increasing depression, anxiety, and irritability (between uses). Each cycle worsens the baseline.',
    warnings: ['Each use causes cumulative neurotoxic damage that cannot be fully reversed', 'Tolerance increases non-linearly — dose escalation leads to overdose risk', 'The neurochemical debt grows with each use, making withdrawal progressively harder'],
  },
  {
    id: 'acute-withdrawal',
    name: 'Acute Withdrawal',
    period: '0-14 Days After Last Use',
    dayRange: '0-14 Days',
    neuroLevel: 25,
    description:
      'Neurotransmitter levels crash dramatically below baseline in the first 24-72 hours after cessation. Without the substance artificially flooding synapses, the brain\'s downregulated receptors cannot process normal neurotransmitter levels. This causes the most intense and dangerous phase of withdrawal: severe anhedonia (complete inability to feel pleasure), profound depression, anxiety, cravings, and in some cases psychosis. Glutamate excitotoxicity peaks during this phase as the compensatory upregulation from active use creates dangerous overexcitation without the dampening effect of the substance. This is the highest-risk phase for relapse, self-harm, and medical complications.',
    symptoms: [
      'Profound anhedonia — nothing brings pleasure',
      'Severe depression with potential suicidal ideation',
      'Intense anxiety, panic attacks, and paranoia',
      'Extreme fatigue alternating with insomnia',
      'Vivid nightmares and sleep disturbances',
      'Intense cravings (peaking days 3-7)',
      'Cognitive dysfunction — brain fog, confusion, poor memory',
      'Physical symptoms: tremors, sweating, nausea, headaches',
      'Emotional volatility — crying spells, anger, hopelessness',
      'Sensory hypersensitivity (light, sound, touch)',
    ],
    neurotransmitterStatus: {
      dopamine: 'Crashed to 10-20% of normal — receptors are downregulated AND neurotransmitter supply is depleted. This causes the profound anhedonia.',
      serotonin: 'Severely depleted — SERT still downregulated, precursor amino acids depleted, synthesis impaired. Sleep and mood are heavily affected.',
      gaba: 'Very low — calming systems are overwhelmed. Anxiety, insomnia, and agitation are dominant. Benzodiazepine withdrawal is particularly dangerous.',
      glutamate: 'Dangerously elevated — compensatory upregulation from active use creates excitotoxic conditions. Can cause seizures in severe cases (especially alcohol/benzo withdrawal).',
      cortisol: 'Extremely high — massive stress response. Further depletes neurotransmitters, damages gut barrier, suppresses immunity.',
    },
    prioritySupplements: [
      { name: 'Magnesium Glycinate', reason: 'CRITICAL: Blocks NMDA receptors to protect against glutamate excitotoxicity. Promotes sleep and reduces anxiety. Foundation supplement.' },
      { name: 'L-Glutamine', reason: 'Repairs gut barrier, supports GABA production, reduces cravings through blood sugar regulation.' },
      { name: 'B-Complex Vitamins', reason: 'All neurotransmitter synthesis pathways require B-vitamins as cofactors. Brain energy metabolism depends on them.' },
      { name: 'Vitamin C', reason: 'Highest oxidative stress period — massive free radical damage. Supports immune system during vulnerability.' },
      { name: 'Melatonin', reason: 'Sleep architecture is completely destroyed. Resetting circadian rhythm is a top priority for recovery.' },
      { name: 'Probiotics', reason: 'Gut barrier is compromised — LPS translocation worsens systemic inflammation and brain fog.' },
    ],
    lifestyleActions: [
      'GET MEDICAL SUPPORT — acute withdrawal can be dangerous, especially from alcohol, benzos, or heavy stimulant use',
      'Prioritize sleep above all else — the brain cannot heal without sleep',
      'Eat small, frequent, nutrient-dense meals even without appetite',
      'Drink electrolyte-rich fluids (coconut water is excellent in the Philippines)',
      'Avoid people, places, and things associated with use',
      'Have a trusted support person available 24/7',
      'Remove all substances and paraphernalia from your environment',
      'Use cold showers for acute anxiety and cravings (activates dive reflex)',
      'Light exercise (walking) — heavy exercise too stressful on the body',
      'Keep a daily journal — track mood, sleep, and triggers',
    ],
    moodExpectation: 'Extremely difficult. Expect the worst moods of your life. This is temporary and is NOT your baseline. Each day the brain recovers a little more. The first 72 hours are the hardest — survival mode.',
    warnings: [
      'DANGER: If you experience seizures, hallucinations, or severe confusion, seek emergency medical help immediately',
      'This is the highest-risk period for relapse — remove all access to substances',
      'Suicidal ideation is common — call 1553 (PH Mental Health Hotline) if you feel unsafe',
      'Do not drive or make major life decisions during this phase',
      'Alcohol/benzo withdrawal can be FATAL without medical supervision',
    ],
  },
  {
    id: 'early-recovery',
    name: 'Early Recovery',
    period: '14-30 Days',
    dayRange: '14-30 Days',
    neuroLevel: 40,
    description:
      'The acute crisis has passed, and the brain enters a rebuilding phase. Neurotransmitter synthesis begins recovering as precursor enzymes (tyrosine hydroxylase, tryptophan hydroxylase) resume normal activity. Dopamine receptors begin the slow process of upregulating back toward normal density. However, the brain is still functioning significantly below baseline, and mood, motivation, and cognitive function remain impaired. Cravings shift from the intense, physical cravings of acute withdrawal to more psychological, cue-triggered cravings. This is the phase where many people relapse because they feel "better" but are still very vulnerable. The gut-brain axis is beginning to repair, with probiotic populations starting to recover.',
    symptoms: [
      'Improving but still low mood — "flat" feeling',
      'Motivation slowly returning but still impaired',
      'Cravings shifting from physical to psychological',
      'Sleep beginning to normalize but still disrupted',
      'Appetite returning (sometimes excessive)',
      'Social anxiety — navigating sober interactions',
      'Brain fog lifting but cognitive function still slow',
      'Emotional reactivity — crying easily, irritability',
      'Occasional "waves" of acute withdrawal symptoms',
      'Growing awareness of damage caused by use',
    ],
    neurotransmitterStatus: {
      dopamine: 'Slowly recovering — synthesis enzymes reactivating, receptors beginning to upregulate. Still at 30-40% of normal. Motivation and pleasure slowly improving.',
      serotonin: 'Beginning to recover — SERT density increasing slowly. Sleep and mood starting to stabilize. Still well below normal.',
      gaba: 'Recovering — natural calming systems coming back online. Anxiety decreasing but still elevated above normal.',
      glutamate: 'Returning toward normal — excitotoxic risk decreasing. Brain becoming less hyperexcitable.',
      cortisol: 'Elevated but decreasing — stress response becoming more regulated. Gut barrier beginning to repair.',
    },
    prioritySupplements: [
      { name: 'L-Tyrosine', reason: 'NOW we support dopamine synthesis — receptors are beginning to upregulate and need neurotransmitters. Morning only.' },
      { name: '5-HTP', reason: 'Serotonin precursor — helps restore mood and sleep. Evening dosing. Cycle 2 weeks on, 1 week off.' },
      { name: 'Omega-3 Fish Oil', reason: 'Brain cell membrane repair and neuroinflammation reduction. EPA for inflammation, DHA for structure.' },
      { name: 'NAC', reason: 'Reduces cravings, supports glutathione, modulates glutamate. Evidence-based for addiction recovery.' },
      { name: 'Zinc Picolinate', reason: 'Testosterone support, immune function, NMDA receptor modulation. Take at night.' },
      { name: 'Alpha-Lipoic Acid', reason: 'Mitochondrial repair — the brain\'s energy factories need recovery support.' },
    ],
    lifestyleActions: [
      'Establish a daily routine — structure is your best friend in early recovery',
      'Begin light exercise (30 min walking daily) — boosts BDNF and dopamine naturally',
      'Attend support group meetings (AA, NA, SMART Recovery, online communities)',
      'Start a sleep hygiene protocol: same bedtime, no screens 1hr before, cool dark room',
      'Eat a nutrient-dense diet: lean protein, vegetables, healthy fats, complex carbs',
      'Practice mindfulness or meditation — even 10 minutes daily rewires stress circuits',
      'Avoid all mind-altering substances including alcohol and cannabis',
      'Identify and avoid your top 5 relapse triggers',
      'Build a sober support network — connect with recovery communities',
      'Consider therapy (CBT, DBT) if accessible',
    ],
    moodExpectation: 'Better than acute withdrawal but still challenging. Moods are more stable but the world still feels somewhat "gray" and flat. Small improvements are noticeable week to week. Patience is essential.',
    warnings: [
      'Relapse risk remains HIGH — "I feel better" is the most dangerous thought in early recovery',
      'PAWS (waves of withdrawal symptoms) can still hit unexpectedly',
      'Avoid "testing" yourself — your brain is still healing',
      'Social situations are major triggers — plan ahead',
      'One use can reset your recovery by weeks',
    ],
  },
  {
    id: 'intermediate-recovery',
    name: 'Intermediate Recovery',
    period: '1-3 Months',
    dayRange: '30-90 Days',
    neuroLevel: 65,
    description:
      'Dopamine receptors have recovered significantly (60-70% of normal), and natural reward processing is returning. The brain is actively rewiring itself through neuroplasticity — new neural pathways are forming that don\'t revolve around substance use. Mood stability improves markedly, and many people report the first genuinely "good" days during this phase. The gut-brain axis is substantially repaired, with healthy probiotic populations reestablished. However, PAWS (Post-Acute Withdrawal Syndrome) can still cause intermittent episodes of anxiety, depression, and cravings that seem to come from nowhere. These PAWS episodes are normal, temporary, and a sign of ongoing brain healing.',
    symptoms: [
      'Increasingly normal mood with periodic PAWS dips',
      'Motivation and drive noticeably improved',
      'Cravings becoming less frequent and less intense',
      'Sleep architecture normalizing — deep sleep returning',
      'Energy levels improving significantly',
      'Cognitive function — memory, focus, decision-making — recovering',
      'Emotional range returning — able to feel joy again',
      'Exercise capacity and physical health improving',
      'Relationships beginning to repair',
      'Periodic "waves" of PAWS (anxiety, low mood, mild cravings)',
    ],
    neurotransmitterStatus: {
      dopamine: '60-70% of normal — D2 receptor density significantly recovered. Natural pleasures (food, socializing, exercise) are becoming rewarding again.',
      serotonin: '70-80% of normal — SERT density approaching baseline. Mood more stable, sleep quality much improved.',
      gaba: 'Near normal — natural calming systems functioning well. Anxiety mostly situational rather than baseline.',
      glutamate: 'Near normal — excitatory/inhibitory balance restored. Cognitive function improving noticeably.',
      cortisol: 'Normalizing — stress response appropriate to situations rather than chronically elevated.',
    },
    prioritySupplements: [
      { name: 'Mucuna Pruriens', reason: 'Natural L-DOPA source for continued dopamine support. Rotate with L-Tyrosine (2 weeks on, 1 week off). Morning only.' },
      { name: 'Ashwagandha', reason: 'HPA axis normalization and cortisol management. Adaptogenic support for stress resilience.' },
      { name: 'Phosphatidylserine', reason: 'Brain cell membrane repair and cognitive enhancement. Supports continued synaptic plasticity.' },
      { name: 'Inositol', reason: 'Reduces residual anxiety and craving patterns. Modulates serotonin and dopamine receptor sensitivity.' },
      { name: 'Vitamin D3 + K2', reason: 'Mood regulation, immune support, bone health. Check blood levels if possible (target 40-60 ng/mL).' },
      { name: 'L-Theanine', reason: 'Daytime calm without sedation. Particularly helpful for social anxiety during reintegration.' },
    ],
    lifestyleActions: [
      'Increase exercise intensity — strength training 3x/week + cardio 3x/week',
      'Deepen your recovery practices: therapy, journaling, meditation',
      'Set and pursue meaningful goals — career, education, relationships',
      'Repair relationships damaged during active use',
      'Build new sober social connections and activities',
      'Practice identifying and managing PAWS episodes when they arrive',
      'Consider nutrition optimization — whole foods, meal prep, adequate protein',
      'Learn new skills or hobbies — neuroplasticity is highest during recovery',
      'Volunteer or help others in recovery — "service work" accelerates your own healing',
      'Create a relapse prevention plan with specific coping strategies',
    ],
    moodExpectation: 'Significantly improved with some setbacks. The "gray" veil is lifting. Genuine moments of joy, humor, and connection are returning. PAWS episodes still happen but are less severe and shorter. Most people report feeling "mostly normal" with occasional difficult days.',
    warnings: [
      'Complacency is the enemy — many relapse at this stage because they feel "recovered"',
      'PAWS episodes can still be intense — have a plan for when they hit',
      'Avoid substituting one addiction for another (food, gambling, screens, etc.)',
      'Social pressure to "just have one" will increase as you feel better',
      'Your tolerance has dropped dramatically — relapse doses can be fatal',
    ],
  },
  {
    id: 'extended-recovery',
    name: 'Extended Recovery',
    period: '3-6 Months',
    dayRange: '90-180 Days',
    neuroLevel: 85,
    description:
      'By 3-6 months, the brain has undergone remarkable recovery. Dopamine receptor density is at 80-90% of normal, serotonin systems are nearly fully restored, and the gut-brain axis is functionally healed. Cognitive function — memory, executive function, emotional processing — has improved dramatically. Many people describe this phase as a "rebirth" where they feel more clear-headed, emotionally stable, and motivated than they have in years (or ever). Neuroplasticity remains elevated, meaning the brain is still actively rewiring. The behavioral patterns established during this period (exercise routines, social connections, coping strategies) become increasingly ingrained as new neural pathways solidify.',
    symptoms: [
      'Mood largely stable with rare, mild fluctuations',
      'Natural reward sensitivity restored — enjoying simple pleasures',
      'Cravings rare and easily dismissed',
      'Sleep quality excellent',
      'High energy and physical vitality',
      'Sharp cognitive function — mental clarity',
      'Emotional intelligence and regulation strong',
      'Confidence in sobriety growing',
      'Occasional nostalgia for substance use (not cravings — just memory)',
      'Feeling genuinely "good" most days',
    ],
    neurotransmitterStatus: {
      dopamine: '80-90% of normal — D2 receptors nearly fully restored. Natural motivation and reward functioning well.',
      serotonin: '85-95% of normal — Mood, sleep, and emotional regulation strong. SERT density near baseline.',
      gaba: 'Normal — stress response appropriate and well-regulated. Healthy calming tone.',
      glutamate: 'Normal — learning, memory, and cognitive function strong. Healthy excitatory/inhibitory balance.',
      cortisol: 'Normal — healthy stress response. HPA axis functioning optimally.',
    },
    prioritySupplements: [
      { name: 'Continue foundational stack', reason: 'Magnesium, Omega-3, B-Complex, Vitamin D3, Probiotics — maintain these as long-term health supplements.' },
      { name: 'Reduce/phase off acute recovery supplements', reason: 'L-Tyrosine, 5-HTP, Mucuna can be reduced or discontinued as natural production normalizes.' },
      { name: 'Focus on optimization supplements', reason: 'Phosphatidylserine, L-Theanine, Ashwagandha for performance and stress resilience.' },
    ],
    lifestyleActions: [
      'Transition supplements from "recovery mode" to "optimal health mode"',
      'Maintain exercise routine — it is now a genuine pleasure, not a chore',
      'Continue therapy if beneficial — work on deeper psychological patterns',
      'Mentor or support newer people in recovery',
      'Pursue meaningful long-term goals',
      'Maintain your recovery community connections',
      'Celebrate milestones — you have achieved something remarkable',
      'Be honest with yourself about any residual triggers',
      'Practice gratitude and mindfulness consistently',
      'Plan for long-term wellness — this is a lifestyle now, not a program',
    ],
    moodExpectation: 'Mostly positive and stable. Genuine enjoyment of life. The world feels vivid and engaging. Occasional difficult days are normal and manageable. Recovery starts to feel like a strength rather than a struggle.',
    warnings: [
      'Overconfidence leads to relapse — "I\'m cured" is a dangerous thought',
      'Some people relapse months or even years into recovery — stay vigilant',
      'New life stressors can trigger old coping patterns',
      'Maintain your support systems even when you feel "fine"',
      'Your brain is still recovering the final 10-15% — full healing takes 1-2 years',
    ],
  },
  {
    id: 'long-term-recovery',
    name: 'Long-Term Recovery',
    period: '6-12+ Months',
    dayRange: '180-365+ Days',
    neuroLevel: 95,
    description:
      'At 6-12 months and beyond, the brain has achieved near-complete recovery for most functions. Dopamine receptor density, serotonin systems, GABA function, and glutamate balance are all within normal ranges. The gut-brain axis is fully healed. Cognitive function, emotional regulation, and physical health have been restored to pre-use levels or better. The neural pathways established during recovery have become dominant, making substance-free life feel natural and automatic. While some subtle cognitive deficits may persist (particularly with heavy, long-term use), most recovering users report that they think more clearly, feel more deeply, and enjoy life more than they did during their using years. The brain\'s neuroplasticity remains elevated, meaning continued growth and adaptation is not just possible but expected.',
    symptoms: [
      'Stable, positive mood with normal emotional range',
      'Strong natural reward sensitivity and motivation',
      'Minimal to no cravings — and when they occur, easily dismissed',
      'Excellent sleep quality',
      'High energy and physical health',
      'Sharp cognitive function',
      'Emotional maturity and resilience',
      'Strong sense of purpose and identity',
      'Healthy relationships and social connections',
      'Genuine confidence and self-worth',
    ],
    neurotransmitterStatus: {
      dopamine: '90-100% of normal — D2 receptors fully restored. Natural reward processing optimal.',
      serotonin: '95-100% of normal — Complete serotonin system recovery. Mood, sleep, and emotional regulation excellent.',
      gaba: 'Normal — Well-regulated stress response. Healthy calming systems.',
      glutamate: 'Normal — Optimal cognitive function. Healthy learning and memory.',
      cortisol: 'Normal — Healthy, appropriate stress response.',
    },
    prioritySupplements: [
      { name: 'Lifelong foundational supplements', reason: 'Magnesium, Omega-3, Vitamin D3, B-Complex, Probiotics — these are for overall health, not just recovery.' },
      { name: 'Adaptogens for optimization', reason: 'Ashwagandha, L-Theanine — for stress resilience and cognitive performance.' },
    ],
    lifestyleActions: [
      'Continue the lifestyle practices that supported your recovery',
      'Help others in recovery — service work is mutually beneficial',
      'Pursue growth: career, education, relationships, fitness',
      'Maintain self-awareness — recovery is a lifelong journey',
      'Celebrate your journey and share your story (when ready)',
      'Stay connected to your recovery community',
      'Continue learning about brain health and optimization',
      'Model healthy living for those around you',
      'Practice ongoing self-care and stress management',
      'Know that your experience gives you wisdom that can help countless others',
    ],
    moodExpectation: 'Consistently positive with natural emotional range. Life feels engaging, meaningful, and worth living. Difficult days are infrequent and manageable. Recovery has become part of your identity and strength.',
    warnings: [
      'Complacency is always the enemy — never say "never relapse"',
      'Major life stressors (loss, trauma, transition) require extra vigilance',
      'Your story can save lives — consider sharing it when ready',
      'Continue investing in your mental and physical health',
    ],
  },
];
