import { SubstanceData } from './types';

const cocaine: SubstanceData = {
    id: 'cocaine',
    name: 'Cocaine',
    aliases: ['Cocaine Hydrochloride', 'Coke', 'Coca', 'Benzoylmethylecgonine', 'Blow'],
    streetNames: ['Coke', 'Crack', 'Snow', 'Blow', 'White Lady', 'Base', 'Rock', 'Tooting'],
    category: 'stimulant',
    schedule: 'Schedule II (PH: Illegal under RA 9165 -- Penalty: Life imprisonment to death for large quantities)',
    dangerLevel: 5,
    description:
      'Cocaine is a powerful central nervous system stimulant derived from the leaves of the Erythroxylum coca plant. It acts primarily by blocking the dopamine transporter (DAT), preventing dopamine reuptake and causing accumulation in the synaptic cleft, producing intense euphoria and reward signaling. Cocaine also blocks serotonin (SERT) and norepinephrine (NET) transporters, contributing to its sympathomimetic effects. Crack cocaine, the freebase form, produces a more rapid and intense high due to faster absorption. Chronic cocaine use causes severe cardiovascular damage (vasoconstriction, hypertension, arrhythmia, myocardial infarction), dopaminergic neurotoxicity, cortical thinning, and profound disruption of the brain\'s reward circuitry. Cocaine use in the Philippines, while less prevalent than methamphetamine, remains a significant concern especially in urban nightlife and among higher socioeconomic groups.',
    primaryDamage: {
      items: [
        'Severe cardiovascular damage (coronary artery vasoconstriction, atherosclerosis acceleration)',
        'Dopamine receptor downregulation and reward circuitry dysfunction',
        'Prefrontal cortex thinning and impaired executive function',
        'Cerebrovascular damage and increased stroke risk',
        'Hepatotoxicity from adulterants and metabolic stress',
        'Cardiomyopathy and weakened heart muscle',
        'Nasal septum perforation (insufflation route)',
        'Cocaine-induced hypercoagulability (increased blood clotting)',
        'Chronic neuroinflammation and microglial activation',
        'Disrupted HPA axis and cortisol dysregulation',
      ],
      summary:
        'Cocaine inflicts damage primarily through intense vasoconstriction and catecholamine excess. The cardiovascular system bears the brunt -- chronic users face dramatically elevated risks of heart attack, stroke, aortic dissection, and arrhythmia. Neurologically, chronic DAT blockade leads to profound dopamine receptor downregulation, rendering the user anhedonic without the drug. The combination of vascular damage and neurotoxicity makes cocaine one of the most organ-destructive substances commonly abused.',
    },
    pharmacology: {
      mechanism:
        'Blocks dopamine transporter (DAT), serotonin transporter (SERT), and norepinephrine transporter (NET), preventing reuptake and causing synaptic accumulation of these monoamines. Also blocks voltage-gated sodium channels (local anesthetic effect). Binds to sigma-1 receptors contributing to psychosis at high doses.',
      halfLife: 'Cocaine HCl: 0.5-1.5 hours; Benzoylecgonine metabolite: 7-12 hours; Cocaethylene (with alcohol): 2-3 hours (more cardiotoxic)',
      onset: 'Insufflated (snorted): 1-5 minutes; IV injection: 15-30 seconds; Smoked (crack): 3-5 seconds; Oral: 10-30 minutes',
      peak: 'Insufflated: 15-30 minutes; IV/Smoked: 1-5 minutes; Oral: 45-90 minutes',
      duration: 'Insufflated: 30-60 minutes; IV/Smoked: 5-15 minutes; Oral: 60-90 minutes',
      metabolites: 'Benzoylecgonine (primary, inactive -- basis for drug testing), Ecgonine methyl ester, Cocaethylene (formed when combined with alcohol -- significantly more cardiotoxic), Norcocaine (hepatotoxic). Metabolized primarily by plasma cholinesterase and liver CYP3A4.',
    },
    withdrawal: {
      timeline: 'Crash: 1-3 days; Acute withdrawal: 1-2 weeks; Subacute: 2-4 weeks; PAWS: months to over a year',
      symptoms: [
        'Profound dysphoria and anhedonia',
        'Intense fatigue and lethargy',
        'Severe cravings (especially in first week)',
        'Depression with potential suicidal ideation',
        'Anxiety and agitation',
        'Increased appetite and weight gain',
        'Vivid/unpleasant dreams and sleep disturbances',
        'Psychomotor retardation and slowed thinking',
        'Paranoia and hypersensitivity to stimuli',
        'Muscle aches and tremors',
      ],
      severity: 'severe',
      paws:
        'Post-Acute Withdrawal Syndrome from cocaine can persist for 6-18 months. Characterized by episodic cravings, anhedonic periods, mood instability, and difficulty experiencing pleasure from normally rewarding activities. Stress is the primary trigger for PAWS episodes. Dopamine receptor recovery is slow but steady, with most users reporting significant improvement by 6-12 months of continuous abstinence.',
    },
    recoveryFocus: {
      neurotransmitters: ['Dopamine', 'Serotonin', 'Norepinephrine', 'GABA', 'Glutamate', 'Endorphins'],
      organs: ['Brain (prefrontal cortex, striatum, reward circuitry)', 'Heart (cardiovascular repair)', 'Liver', 'Nasal passages (if snorted)'],
      prioritySupplements: [
        'L-Tyrosine',
        'N-Acetyl Cysteine (NAC)',
        'Magnesium Glycinate',
        'Omega-3 Fish Oil',
        'L-Glutamine',
        'Alpha-Lipoic Acid',
        'B-Complex Vitamins',
        'Coenzyme Q10 (CoQ10)',
        'Vitamin C',
        'Rhodiola Rosea',
      ],
      timeline:
        'Days 1-7: Intense crash, dopamine depletion, cravings peak. Days 7-14: Acute withdrawal subsides, energy slowly returns. Weeks 2-4: Sleep normalizes, mood begins stabilizing. Months 1-3: Dopamine receptors begin upregulating, cravings diminish. Months 3-6: Significant recovery of reward sensitivity. Months 6-12: Near-normal dopamine function, cardiovascular risks decrease. Full recovery: 12-18 months for complete neuroadaptation.',
    },
    philippines: {
      legality: 'Illegal under Republic Act No. 9165. Cocaine and crack cocaine are classified as dangerous drugs. Possession, sale, manufacture, and use are criminal offenses with severe penalties.',
      penalties: 'Possession of small quantity: 6 months + 4 years imprisonment + fine up to ₱500,000. Sale/trading: 12 years + 1 day to 20 years + fine up to ₱10,000,000. Importation/manufacturing: Life imprisonment to death + fine up to ₱50,000,000. Repeat offenses carry enhanced penalties.',
      commonForm: 'Cocaine hydrochloride powder (white crystalline powder, typically snorted). Crack cocaine (freebase "rocks" smoked in glass pipes) is less common but exists. Occasionally found as liquid for injection. Often adulterated with levamisole, lidocaine, or caffeine in the Philippine market.',
      streetPrice: '₱2,000-5,000 per gram (powder). ₱500-1,500 per "bump" or small bag. Crack rocks: ₱300-800 per piece. Prices are significantly higher than methamphetamine due to import costs. Availability varies -- more common in Metro Manila, Cebu, and Boracay entertainment districts.',
    },
    harmReduction: [
      'Never use cocaine with alcohol -- forms cocaethylene, a compound 30% more cardiotoxic than cocaine alone',
      'Start with the smallest possible amount and avoid redosing after the first hour',
      'Stay hydrated with electrolytes but avoid excessive water intake (syndrome of inappropriate ADH risk)',
      'Monitor your heart rate -- if resting HR exceeds 110bpm or you feel chest pain, seek emergency care immediately',
      'Avoid mixing with other stimulants, Viagra (dangerous hypertensive interactions), or opioids',
      'Use clean equipment and never share straws or needles to prevent hepatitis and HIV transmission',
      'Limit use frequency -- cardiotoxicity is cumulative even with "moderate" use',
      'Eat a nutritious meal before use -- cocaine suppresses appetite and depletes nutrients',
      'Allow minimum 48-72 hours between uses to allow dopamine and serotonin partial recovery',
      'Know the signs of cocaine-induced heart attack: chest pain, shortness of breath, left arm pain -- call emergency services immediately',
    ],
    recoveryTips: [
      'Exercise daily -- even 30 minutes of walking dramatically accelerates dopamine receptor recovery',
      'Take L-tyrosine on an empty stomach in the morning to support natural dopamine production',
      'Avoid sugar and processed foods during early recovery -- they can trigger cravings by artificially stimulating reward pathways',
      'Cold showers can help reduce cravings and improve mood through endorphin release',
      'Track your triggers in a journal -- awareness of patterns is your strongest defense against relapse',
    ],
    recoveryPhases: [
      {
        name: 'Acute Withdrawal -- The Crash',
        timeline: 'Days 0-14',
        prioritySupplements: [
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'Ashwagandha', dosage: '300-600mg' },
          { name: 'CoQ10', dosage: '100-200mg' },
          { name: 'Hawthorn', dosage: '300-600mg' },
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'NAC', dosage: '600-1200mg' },
          { name: 'B6', dosage: '25-50mg' },
        ],
        dietaryFocus: [
          'High-protein foods (chicken, fish, eggs)',
          'Complex carbohydrates (brown rice, oats)',
          'Potassium-rich foods (bananas, sweet potatoes)',
          'Fresh fruits and vegetables daily',
          'Avoid caffeine and stimulants',
        ],
        milestones: ['first_24h_clean', 'blood_pressure_monitored', 'cravings_acknowledged', 'first_night_sleep'],
      },
      {
        name: 'Early Recovery -- Cardiovascular Watch',
        timeline: 'Days 14-60',
        prioritySupplements: [
          { name: 'L-Tyrosine', dosage: '500-1500mg' },
          { name: 'CoQ10', dosage: '100-200mg' },
          { name: 'Hawthorn', dosage: '300-600mg' },
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'Ashwagandha', dosage: '300-600mg' },
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'NAC', dosage: '600-1200mg' },
          { name: 'B6', dosage: '25-50mg' },
        ],
        dietaryFocus: [
          'Tyrosine-rich foods (eggs, chicken, dairy)',
          'Omega-3 sources (fatty fish 3x/week)',
          'Antioxidant-rich berries and leafy greens',
          'Regular meals to stabilize blood sugar',
          'Limit processed foods and sodium',
        ],
        milestones: ['two_weeks_clear', 'bp_trending_normal', 'endothelial_healing', 'dopamine_rebuilding'],
      },
      {
        name: 'Rebuilding -- Dopamine & Cardio Recovery',
        timeline: 'Months 2-6',
        prioritySupplements: [
          { name: 'L-Tyrosine', dosage: '500-1500mg' },
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'CoQ10', dosage: '100-200mg' },
          { name: 'Creatine', dosage: '3-5g' },
          { name: 'Hawthorn', dosage: '300-600mg' },
          { name: 'Turmeric', dosage: '500-1000mg' },
          { name: 'B6', dosage: '25-50mg' },
        ],
        dietaryFocus: [
          'Brain-supportive foods: fatty fish, walnuts, blueberries',
          'High-quality protein at every meal',
          ' Mediterranean-style diet (olive oil, vegetables, whole grains)',
          'Exercise to boost BDNF and cardiovascular health',
          'Moderate caffeine only (1 cup/day)',
        ],
        milestones: ['two_months_clear', 'anhedonia_easing', 'cardiovascular_improving', 'exercise_capacity_up'],
      },
      {
        name: 'Maintenance -- Cardiovascular Vigilance',
        timeline: 'Month 6+',
        prioritySupplements: [
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'CoQ10', dosage: '100-200mg' },
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'Turmeric', dosage: '500-1000mg' },
          { name: 'B6', dosage: '25-50mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
        ],
        dietaryFocus: [
          'Mediterranean-style diet adapted to PH',
          'Continue antioxidant-rich fruits: papaya, mango, guava',
          'Regular cardiovascular exercise (150 min/week)',
          'Regular sleep schedule (7-8 hours)',
          'Social meals and community connection',
        ],
        milestones: ['six_months_clear', 'cardio_stable', 'dopamine_recovered', 'long_term_health_plan'],
      },
    ],
  };

export default cocaine;
