import { SubstanceData } from './types';

const ghb: SubstanceData = {
    id: 'ghb',
    name: 'GHB (Gamma-Hydroxybutyrate)',
    aliases: ['Gamma-Hydroxybutyrate', 'Sodium Oxybate', '4-Hydroxybutanoic Acid', 'GBH', 'G'],
    streetNames: ['G', 'Liquid Ecstasy', 'Gina', 'Liquid E', 'Georgia Home Boy', 'Soap', 'Fantasy', 'Cherry Meth'],
    category: 'depressant',
    schedule: 'Schedule I (PH: Illegal under RA 9165 -- Penalty similar to other dangerous drugs)',
    dangerLevel: 4,
    description:
      'GHB (gamma-hydroxybutyrate) is a naturally occurring short-chain fatty acid that acts as both a GABA-B receptor agonist and a GABA-A receptor modulator at higher concentrations. It is also an endogenous neuromodulator derived from GABA metabolism. GHB produces dose-dependent effects: at low doses it causes euphoria, sociability, and relaxation (similar to alcohol); at moderate doses it induces sedation and sleep; at high doses it causes deep unconsciousness, respiratory depression, and potentially fatal coma. GHB is particularly dangerous because the therapeutic index is very narrow -- the difference between a recreational dose and an overdose can be as little as 1-2ml. The drug has gained notoriety as a "date rape drug" due to its sedative and amnesia-inducing properties combined with its colorless, odorless nature when dissolved in beverages. Chronic GHB use leads to severe GABA-B receptor downregulation, producing a withdrawal syndrome that is among the most dangerous of all substances, with risks of delirium, psychosis, and death. Bodybuilders have also misused GHB for its purported growth hormone-releasing effects.',
    primaryDamage: {
      items: [
        'GABA-B receptor downregulation and functional tolerance',
        'Severe respiratory depression risk (narrow therapeutic index)',
        'Dangerous withdrawal syndrome (delirium, psychosis, seizures, cardiovascular collapse)',
        'Rapid onset unconsciousness with high risk of aspiration/asphyxiation',
        'Amnesia and dissociation during intoxication (facilitating assault risk)',
        'Disrupted sleep architecture despite sedative use (reduced REM, disrupted slow-wave sleep)',
        'Metabolic acidosis during overdose',
        'Cardiovascular instability (bradycardia, hypotension)',
        'Urinary/fecal incontinence during unconsciousness',
        'Potential neurotoxicity with chronic high-dose use',
      ],
      summary:
        'GHB is uniquely dangerous due to its extremely narrow therapeutic index -- a dose only slightly above the recreational range can cause deep coma and death from respiratory arrest. The drug\'s rapid onset and short duration often lead users to redose frequently, dramatically increasing overdose risk. GHB withdrawal is considered one of the most medically dangerous withdrawal syndromes, potentially exceeding alcohol and benzodiazepine withdrawal in severity. The combination of GABA-B receptor downregulation and the short half-life creates a state of profound neural hyperexcitability upon cessation that requires intensive medical management.',
    },
    pharmacology: {
      mechanism:
        'Acts as a full agonist at GABA-B receptors (the same receptors targeted by baclofen), producing inhibitory effects. At higher concentrations, also modulates GABA-A receptors. Binds to specific GHB receptors (GPR172A) which are distinct from GABA receptors. Stimulates growth hormone release via hypothalamic mechanisms. The euphoric effects are mediated primarily through GABA-B activation in the ventral tegmental area (VTA), indirectly modulating dopamine release. Also increases endogenous opioid activity.',
      halfLife: '20-60 minutes (very short). This extremely short half-life necessitates frequent redosing and contributes to severe withdrawal when discontinued. Users typically dose every 2-4 hours.',
      onset: 'Oral (liquid): 10-20 minutes; onset is faster on an empty stomach',
      peak: 'Oral: 20-60 minutes',
      duration: 'Oral: 1.5-3 hours (short duration leads to frequent redosing cycle)',
      metabolites: 'GHB is metabolized to succinic semialdehyde by GHB dehydrogenase, then to succinic acid (enters Krebs cycle). Small amounts metabolized to GABA. Less than 5% excreted unchanged in urine. Not metabolized by CYP450 enzymes -- minimal drug interaction through hepatic metabolism. Sodium GHB (sodium oxybate/Xyrem) is the pharmaceutical form.',
    },
    withdrawal: {
      timeline: 'Onset: 1-6 hours after last dose (rapid due to short half-life). Peak: 24-72 hours. Acute: 5-14 days. Protracted: weeks to months',
      symptoms: [
        'Severe anxiety, agitation, and panic attacks',
        'Tremors, muscle rigidity, and myoclonic jerks',
        'Delirium with hallucinations and confusion',
        'Autonomic instability (tachycardia, hypertension, diaphoresis)',
        'Seizures (generalized, potentially status epilepticus)',
        'Severe insomnia (inability to sleep for days)',
        'Paranoid psychosis (may persist for weeks)',
        'Nausea, vomiting, and dehydration',
        'Tachycardia and palpitations',
        'Profound disorientation and cognitive confusion',
      ],
      severity: 'critical',
      paws:
        'Post-Acute Withdrawal Syndrome from GHB can persist for 6-18 months. Characterized by persistent anxiety, sleep disturbances (insomnia, altered sleep architecture), mood instability, cognitive dysfunction, periodic craving waves, and intermittent autonomic symptoms. GABA-B receptor recovery is gradual. Users who withdrew without medical supervision report prolonged psychological symptoms including anxiety disorders that were not present before GHB use. The high frequency of dosing creates deeply ingrained behavioral patterns that require extensive psychological support to overcome.',
    },
    recoveryFocus: {
      neurotransmitters: ['GABA (GABA-B and GABA-A)', 'Glutamate', 'Dopamine', 'Serotonin', 'Endorphins'],
      organs: ['Brain (GABA-B receptor density)', 'Heart (cardiovascular stabilization)', 'Liver', 'Nervous system'],
      prioritySupplements: [
        'L-Theanine',
        'Magnesium Glycinate',
        'Ashwagandha',
        'Passionflower Extract',
        'B-Complex Vitamins',
        'L-Glutamine',
        'Probiotics',
        'Omega-3 Fish Oil',
        'Taurine (GABA-A modulator)',
        '5-HTP',
      ],
      timeline:
        'Days 1-7: Intensive medical detox recommended (high risk of delirium/seizures). Days 7-14: Acute symptoms gradually subside, sleep may begin returning. Weeks 2-4: Anxiety decreases, cognitive function improves, autonomic symptoms resolve. Months 1-3: GABA-B receptors begin normalizing, mood stabilizes. Months 3-6: Significant recovery, sleep architecture normalizes. Months 6-12: Continued improvement, PAWS episodes become less frequent. Full recovery: 12-18 months for complete GABAergic recovery.',
    },
    philippines: {
      legality: 'Illegal under Republic Act No. 9165. GHB and its precursors (GBL, 1,4-butanediol) are classified as dangerous drugs. Possession, manufacture, sale, and use are criminal offenses. The drug\'s association with drug-facilitated sexual assault has led to additional attention from law enforcement.',
      penalties: 'Possession: 6 months + 4 years imprisonment + fine up to ₱500,000. Sale/trading: 12 years + 1 day to 20 years + fine up to ₱10,000,000. Manufacturing/importation: Life imprisonment to death + fine up to ₱50,000,000. Enhanced penalties if used in the commission of sexual assault.',
      commonForm: 'Clear, colorless liquid with a slightly salty or soapy taste (often disguised in water or alcoholic drinks). Sodium salt form as crystalline powder (dissolved in liquid before use). Concentration varies wildly in illicit preparations, making accurate dosing extremely difficult and dangerous. Bodybuilders sometimes obtain GHB or GBL (precursor) through illicit channels.',
      streetPrice: '₱200-500 per small bottle/vial (single dose). ₱1,000-3,000 per larger bottle (multiple doses). GBL (precursor): ₱500-1,500 per bottle. Prices vary and availability is sporadic, more common in nightclub scenes and bodybuilding communities in Metro Manila.',
    },
    harmReduction: [
      'Measure doses precisely with a calibrated syringe -- NEVER estimate by cap or bottle size (concentration varies wildly)',
      'Start with a very low test dose (0.5-1ml) when using any new batch -- overdose threshold is dangerously close to recreational dose',
      'Wait 2-3 hours before redosing -- GHB effects stack rapidly and redosing too soon causes sudden coma',
      'NEVER mix with alcohol, benzodiazepines, or other CNS depressants -- exponentially increases respiratory depression risk',
      'Never use alone -- unconsciousness can occur rapidly and without warning',
      'Write down the time and dose of each administration to prevent accidental overdose from redosing',
      'Keep the person on their side (recovery position) if they lose consciousness to prevent aspiration',
      'Be aware of the "GHB coma" -- if someone is unarousable, call emergency services immediately',
      'Watch your drink in social settings -- GHB has been used as a predatory drug',
      'If dependent, seek medically supervised detox -- GHB withdrawal can be fatal without medical management',
    ],
    recoveryTips: [
      'Medical detox is essential -- GHB withdrawal carries risk of delirium and cardiovascular collapse',
      'GABA-B receptor recovery is gradual -- be patient with sleep disturbances and anxiety',
      'Structured sleep hygiene (consistent bedtime, no screens) helps normalize circadian rhythm disrupted by GHB',
      'Regular meals with complex carbohydrates stabilize blood sugar and reduce mood swings',
      'Build a sober support network -- isolation is the primary predictor of GHB relapse',
    ],
    recoveryPhases: [
      {
        name: 'Acute Withdrawal -- MEDICAL SUPERVISION REQUIRED',
        timeline: 'Days 0-14',
        neurochemicalState: 'GABA-B receptors severely downregulated. GABA-A compensatory upregulation. Glutamate hyperactive. Seizure risk极高.',
        medicalNote: 'GHB/GBL withdrawal can be life-threatening. Seizures, delirium, and cardiovascular collapse risk. Medical supervision is MANDATORY.',
        prioritySupplements: [
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'Buko Juice (Coconut Water)', dosage: '1-3 glasses' },
          { name: 'L-Glutamine', dosage: '5-10g' },
          { name: 'Ashwagandha', dosage: '300-600mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
          { name: 'NAC', dosage: '600-1200mg' },
          { name: 'Prebiotic Inulin', dosage: '5-10g' },
        ],
        dietaryFocus: [
          'Electrolyte-rich foods (coconut water, bananas, potatoes)',
          'Easily digestible meals (soup, rice porridge)',
          'Frequent small meals to stabilize blood sugar',
          'Avoid sugar spikes and processed foods',
          'Hydration: 2-3L water + buko juice daily',
        ],
        milestones: ['medical_supervision_obtained', 'first_72h_stable', 'electrolytes_normalizing', 'seizure_free'],
      },
      {
        name: 'Early Recovery -- GABA Rebalancing',
        timeline: 'Days 14-60',
        prioritySupplements: [
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'Ashwagandha', dosage: '300-600mg' },
          { name: 'L-Glutamine', dosage: '5-10g' },
          { name: 'Buko Juice', dosage: '1-3 glasses' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
          { name: 'Prebiotic Inulin', dosage: '5-10g' },
          { name: 'Omega-3', dosage: '2000-4000mg' },
        ],
        dietaryFocus: [
          'Complex carbohydrates (brown rice, camote, oats)',
          'Protein at every meal for GABA precursor amino acids',
          'Magnesium-rich foods (dark leafy greens, pumpkin seeds)',
          'Fermented foods for gut healing',
          'Regular sleep schedule priority',
        ],
        milestones: ['two_weeks_medically_stable', 'first_natural_sleep', 'anxiety_decreasing', 'gaba_receptors_recovering'],
      },
      {
        name: 'Rebuilding -- Nervous System Recovery',
        timeline: 'Months 2-6',
        prioritySupplements: [
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'Ashwagandha', dosage: '300-600mg' },
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
          { name: 'L-Glutamine', dosage: '5-10g' },
          { name: 'Creatine', dosage: '3-5g' },
        ],
        dietaryFocus: [
          'Brain-supportive foods: fatty fish, walnuts, eggs',
          'Regular exercise to support GABA production',
          'Balanced meals with complex carbs and protein',
          'Anti-inflammatory foods: turmeric, ginger, green tea',
          'Stress management through routine and structure',
        ],
        milestones: ['two_months_stable', 'sleep_nearly_normal', 'cognitive_clarity_returning', 'anxiety_manageable'],
      },
      {
        name: 'Maintenance -- Long-Term Stability',
        timeline: 'Month 6+',
        prioritySupplements: [
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
          { name: 'Ashwagandha', dosage: '300-600mg' },
        ],
        dietaryFocus: [
          'Balanced Mediterranean-style diet adapted to PH',
          'Regular sleep schedule (7-8 hours)',
          'Regular exercise for nervous system health',
          'Social connection and community activities',
          'Stress management practices maintained',
        ],
        milestones: ['six_months_clear', 'gaba_system_restored', 'sleep_quality_excellent', 'long_term_stability'],
      },
    ],
  };

export default ghb;
