import { SubstanceData } from './types';

const mdma: SubstanceData = {
    id: 'mdma',
    name: 'MDMA (3,4-Methylenedioxymethamphetamine)',
    aliases: ['Ecstasy', 'Molly', 'MDMA', 'XTC', 'Adam', 'Eve', 'Dove'],
    streetNames: ['Pills', 'Beans', 'Roses', 'Chocolates', 'Yakults', 'X', 'E'],
    category: 'empathogen',
    schedule: 'Schedule I (PH: Illegal under RA 9165)',
    dangerLevel: 4,
    description:
      'MDMA is an empathogen-entactogen primarily acting as a serotonin-releasing agent and reuptake inhibitor (SRA/SRI). It causes massive serotonin efflux by reversing the serotonin transporter (SERT), while also moderately affecting dopamine and norepinephrine systems. The drug produces characteristic feelings of euphoria, emotional openness, and enhanced sensory perception. However, acute use causes significant serotonergic neurotoxicity through oxidative stress, hyperthermia, and metabolite-induced damage (particularly from HHMA and HMMA metabolites). Chronic use leads to profound serotonin depletion, SERT downregulation, and lasting mood dysregulation. Recovery focuses on serotonin restoration, protecting serotonergic neurons from further damage, and rebuilding the emotional regulation systems that MDMA disrupts. In the Philippines, MDMA is commonly found in pill form at clubs and parties.',
    primaryDamage: {
      items: [
        'Severe serotonin depletion and SERT (serotonin transporter) downregulation',
        'Oxidative stress to serotonergic neurons via metabolites (HHMA, HMMA)',
        'Disrupted thermoregulation leading to hyperthermia-related organ damage',
        'Hippocampal neurotoxicity affecting memory consolidation',
        'Axonal degeneration in serotonergic nerve terminals',
        'Endothelial dysfunction and cardiovascular strain',
        'Liver toxicity from metabolic processing',
        'Disrupted HPA axis (cortisol dysregulation)',
        'Depletion of antioxidant defenses (glutathione, Vitamin C)',
        'Impaired executive function and emotional processing',
      ],
      summary:
        'MDMA causes selective neurotoxicity to the serotonergic system through multiple converging mechanisms: direct serotonin depletion, oxidative stress from metabolites, hyperthermia-induced protein denaturation, and excitotoxicity. The hippocampus and prefrontal cortex are particularly vulnerable. Long-term users show reduced SERT density (up to 30-50% reduction), impaired verbal memory, and chronic serotonergic dysfunction that can persist for months to years after cessation.',
    },
    pharmacology: {
      mechanism:
        'Reverses SERT causing massive serotonin efflux; moderately reverses DAT (dopamine) and NET (norepinephrine). Also acts as a weak MAO-A inhibitor. Binding to 5-HT2B receptors contributes to cardiac valvulopathy with chronic use. The empathogenic effects are primarily mediated by serotonin release in the amygdala and prefrontal cortex.',
      halfLife: '7-9 hours (active metabolites up to 16 hours)',
      onset: 'Oral: 20-60 minutes; Snorted: 5-10 minutes (rare route); Rectal: 10-15 minutes',
      peak: 'Oral: 1.5-2.5 hours (peak effects)',
      duration: 'Oral: 3-6 hours (primary effects); After-effects: 2-8 hours ("comedown")',
      metabolites:
        'MDA (active, neurotoxic), HHMA (dihydroxymethamphetamine), HMMA (hydroxymethamphetamine). Primary metabolism via CYP2D6 enzyme.',
    },
    withdrawal: {
      timeline: 'Acute comedown: 1-3 days; Subacute: 1-2 weeks; Serotonin recovery: weeks to months',
      symptoms: [
        'Profound depression and emotional blunting ("Tuesday blues")',
        'Anxiety and panic (especially in social situations)',
        'Fatigue and lethargy',
        'Difficulty concentrating and brain fog',
        'Irritability and mood swings',
        'Sleep disturbances (insomnia, vivid dreams)',
        'Loss of appetite or comfort eating',
        'Decreased libido',
        'Memory problems (short-term and verbal)',
        'Cravings (often triggered by music, social settings)',
      ],
      severity: 'moderate',
      paws:
        'PAWS from MDMA is characterized by persistent emotional blunting, intermittent depressive episodes, social anxiety, and cognitive fog. Serotonin recovery is slow -- SERT density can take 3-6 months to normalize. Users report that the first 2-4 weeks after stopping are the most difficult, with gradual improvement thereafter. Full emotional recovery may take 6-12 months depending on usage history.',
    },
    recoveryFocus: {
      neurotransmitters: ['Serotonin', 'Dopamine', 'GABA', 'Melatonin'],
      organs: ['Brain (serotonergic neurons, hippocampus)', 'Liver', 'Heart (valvular health)', 'Gut (serotonin production -- 95% of body\'s serotonin)'],
      prioritySupplements: [
        '5-HTP',
        'L-Tryptophan',
        'Magnesium Glycinate',
        'Vitamin C',
        'Alpha-Lipoic Acid',
        'Probiotics',
        'Omega-3 Fish Oil',
        'L-Theanine',
        'B-Complex Vitamins',
        'Melatonin',
      ],
      timeline:
        'Days 1-7: Acute serotonin depletion, emotional crash. Weeks 1-4: Initial SERT upregulation begins, mood slowly stabilizes. Months 1-3: Significant serotonin recovery, emotional range returns. Months 3-6: SERT density approaches normal, memory improves. Months 6-12: Full serotonergic recovery for most users. Complete recovery possible within 6-18 months for moderate users.',
    },
    philippines: {
      legality: 'Illegal under Republic Act No. 9165. Classified as a dangerous drug. Possession, sale, and manufacture carry severe penalties.',
      penalties: 'Similar to methamphetamine penalties. Possession: 6 months + 4 years imprisonment + fine up to ₱500,000. Sale/trading: 12 years + 1 day to 20 years + fine up to ₱10,000,000.',
      commonForm: 'Pressed pills in various colors/stamps (branded pills like "Tesla", "Chanel", "Rolex logos). Also found as crystalline powder ("Molly") though purity varies significantly. Commonly sold at clubs, parties, and festivals.',
      streetPrice: '₱300-800 per pill. ₱1,500-3,000 per gram (crystal). Pill price varies by brand/stamp and venue. Party/festival prices are typically higher.',
    },
    harmReduction: [
      'Test your substance -- many "MDMA" pills contain methamphetamine, cathinones, or fentanyl in the Philippines',
      'Limit to once per 2-3 month minimum -- neurotoxicity is cumulative and dose-dependent',
      'Stay cool and hydrated -- sip 250-500ml water per hour, avoid overheating',
      'Take antioxidant preload (Vitamin C 1g, Alpha-Lipoic Acid 200mg) 1 hour before',
      'Post-load with 5-HTP (50-100mg) and magnesium after the experience',
      'Avoid SSRIs/MAOIs -- life-threatening serotonin syndrome risk',
      'Don\'t mix with alcohol (increases dehydration and liver toxicity)',
      'Take breaks from dancing to prevent rhabdomyolysis',
      'Have a trusted "trip sitter" who is sober',
      'Start with a test dose (quarter pill) if using a new batch',
    ],
    recoveryTips: [
      'Serotonin recovery takes 2-4 weeks of abstinence -- mood will gradually stabilize',
      '5-HTP (50-100mg) with a small carbohydrate meal can support serotonin production during recovery',
      'MDMA depletes magnesium -- supplement 400mg daily to reduce jaw clenching, muscle tension, and anxiety',
      'Antioxidant supplementation (Vitamin C, alpha-lipoic acid) before and after use reduces oxidative neurotoxicity',
      'Psychological integration of MDMA experiences with a therapist amplifies long-term benefits',
    ],
    recoveryPhases: [
      {
        name: 'Post-Roll Comedown -- Serotonin Depletion',
        timeline: 'Days 0-7',
        prioritySupplements: [
          { name: '5-HTP', dosage: '150-300mg' },
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'EGCG', dosage: '200-400mg' },
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'B6', dosage: '25-50mg' },
          { name: 'NAC', dosage: '600-1200mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
        ],
        dietaryFocus: [
          'Tryptophan-rich foods (turkey, eggs, pumpkin seeds)',
          'Complex carbohydrates (support serotonin production)',
          'Fresh fruits and vegetables',
          'Hydration: 2-3L water daily',
          'Avoid alcohol and other drugs during recovery window',
        ],
        milestones: ['first_24h_post_roll', 'serotonin_precursor_started', 'temperature_normalized'],
      },
      {
        name: 'SERT Recovery Window',
        timeline: 'Days 7-28',
        prioritySupplements: [
          { name: '5-HTP', dosage: '150-300mg' },
          { name: 'EGCG', dosage: '200-400mg' },
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'B6', dosage: '25-50mg' },
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'Turmeric', dosage: '500-1000mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
        ],
        dietaryFocus: [
          'Serotonin-supportive diet (eggs, cheese, nuts, salmon)',
          'Anti-inflammatory foods (berries, leafy greens)',
          'Regular sleep schedule for serotonin rhythm restoration',
          'Light exercise (walking, yoga)',
          'Mindful eating -- regular meal times',
        ],
        milestones: ['one_week_post_roll', 'mood_stabilizing', 'sleep_quality_returning'],
      },
      {
        name: 'Neuroregeneration Phase',
        timeline: 'Months 1-3',
        prioritySupplements: [
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: '5-HTP', dosage: '150-300mg' },
          { name: 'Turmeric', dosage: '500-1000mg' },
          { name: 'Creatine', dosage: '3-5g' },
          { name: 'EGCG', dosage: '200-400mg' },
          { name: 'B6', dosage: '25-50mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
        ],
        dietaryFocus: [
          'Brain-supportive foods: fatty fish, walnuts, blueberries',
          'Antioxidant-rich fruits and vegetables',
          'Regular exercise for BDNF production',
          'Consistent sleep-wake cycle',
          'Social connection and meaningful activities',
        ],
        milestones: ['one_month_clear', 'memory_improving', 'serotonin_levels_normal', 'emotional_range_returning'],
      },
      {
        name: 'Long-Term Neuroprotection',
        timeline: 'Month 3+',
        prioritySupplements: [
          { name: 'Omega-3', dosage: '2000-4000mg' },
          { name: 'Turmeric', dosage: '500-1000mg' },
          { name: 'B6', dosage: '25-50mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
          { name: 'Creatine', dosage: '3-5g' },
        ],
        dietaryFocus: [
          'Mediterranean-style diet adapted to PH',
          'Regular omega-3 intake (fish 3x/week)',
          'Balanced nutrition for long-term brain health',
          'Regular exercise and stress management',
          'Community connection and purpose',
        ],
        milestones: ['three_months_clear', 'full_emotional_range', 'harm_reduction_knowledge', 'peer_support_active'],
      },
    ],
  };

export default mdma;
