import { SubstanceData } from './types';

const methamphetamine: SubstanceData = {
    id: 'methamphetamine',
    name: 'Methamphetamine',
    aliases: ['Meth', 'Crystal Meth', 'D-Methamphetamine', 'Desoxyephedrine'],
    streetNames: ['Shabu', 'Tina', 'Basura', 'Bato', 'Crystal', 'Ice', 'Glass', 'Krokodil (misnomer)'],
    category: 'stimulant',
    schedule: 'Schedule II (PH: Dangerous Drugs Act - Penalty: Life imprisonment to death)',
    dangerLevel: 5,
    description:
      'Methamphetamine is a potent central nervous system stimulant that floods the brain with dopamine, norepinephrine, and serotonin at up to 10x normal levels. It works by reversing the direction of dopamine transporter (DAT) and vesicular monoamine transporter 2 (VMAT-2) proteins, causing massive neurotransmitter efflux into the synaptic cleft. Chronic use causes severe dopamine receptor downregulation, neurotoxicity via oxidative stress and excitotoxicity, gut barrier destruction through vasoconstriction of intestinal blood vessels, and HPG axis suppression leading to testosterone deficiency in male users. Recovery involves rebuilding dopaminergic function, repairing the gut-brain axis, restoring hormonal balance, and addressing the profound anhedonia that characterizes early abstinence. The Philippines is one of the highest consumers of methamphetamine globally, with "shabu" being the most prevalent form.',
    primaryDamage: {
      items: [
        'Severe dopamine receptor downregulation (D2 receptor blunting)',
        'Gut dysbiosis and intestinal permeability (leaky gut)',
        'HPG axis suppression (low testosterone in males)',
        'Neuroinflammation via chronic microglial activation',
        'Sleep architecture destruction (REM suppression)',
        'Cardiovascular stress (tachycardia, hypertension, arrhythmia)',
        'Oxidative stress and mitochondrial damage',
        'White matter degradation and reduced prefrontal cortex volume',
        'Dental destruction ("meth mouth" - bruxism, dry mouth, poor nutrition)',
        'Glutamate excitotoxicity causing neuronal apoptosis',
      ],
      summary:
        'Methamphetamine causes widespread neurodegeneration through multiple pathways: direct neurotoxicity, oxidative stress, excitotoxicity, and vascular damage. The brain\'s reward circuitry is fundamentally altered, with D2 receptor density dropping by up to 50% in chronic users. The gut-brain axis is severely compromised through vasoconstriction-induced ischemia of intestinal tissue, leading to bacterial translocation and systemic inflammation.',
    },
    pharmacology: {
      mechanism:
        'Reverses DAT and VMAT-2 transporters causing massive dopamine efflux into synaptic cleft; also releases norepinephrine and serotonin. Inhibits monoamine oxidase (MAO), extending neurotransmitter activity. Crosses blood-brain barrier rapidly due to high lipophilicity.',
      halfLife: '10-12 hours (extended: up to 30+ hours with binge use)',
      onset: 'Smoked/injected: 3-5 seconds (rush); Oral: 15-20 minutes; Snorted: 3-5 minutes',
      peak: 'Smoked/injected: 1-5 minutes; Oral: 2-4 hours',
      duration: 'Smoked/injected: 8-12 hours; Oral: 10-24 hours',
      metabolites: 'Amphetamine (active), p-OH-amphetamine, norephedrine. Excreted renally with 30-54% unchanged.',
    },
    withdrawal: {
      timeline: 'Acute: 1-14 days; Subacute: 2-4 weeks; PAWS: months to years',
      symptoms: [
        'Profound anhedonia (inability to feel pleasure)',
        'Extreme fatigue and hypersomnia',
        'Depression (can be severe with suicidal ideation)',
        'Anxiety and panic attacks',
        'Intense cravings (especially in first 2 weeks)',
        'Cognitive impairment (brain fog, poor concentration)',
        'Increased appetite',
        'Vivid nightmares and sleep disturbances',
        'Psychomotor retardation',
        'Paranoia and perceptual disturbances',
      ],
      severity: 'severe',
      paws:
        'Post-Acute Withdrawal Syndrome can persist for 6-24 months, characterized by intermittent waves of anhedonia, depression, cognitive dysfunction, and cravings triggered by stress, people, places, or cues associated with previous use. Each wave is typically less intense and shorter in duration than the previous one.',
    },
    recoveryFocus: {
      neurotransmitters: ['Dopamine', 'Serotonin', 'Norepinephrine', 'GABA', 'Glutamate'],
      organs: ['Brain (prefrontal cortex, striatum)', 'Gut (microbiome, intestinal lining)', 'Liver (detoxification)', 'Heart (cardiovascular repair)'],
      prioritySupplements: [
        'Magnesium Glycinate',
        'N-Acetyl Cysteine (NAC)',
        'L-Tyrosine',
        'L-Glutamine',
        'Mucuna Pruriens',
        'Alpha-Lipoic Acid',
        'B-Complex Vitamins',
        'Probiotics',
        'Zinc Picolinate',
        'Vitamin D3',
      ],
      timeline:
        'Days 1-14: Acute withdrawal, neurotransmitter crash. Days 14-30: Early recovery, receptors begin upregulating. Months 1-3: Dopamine recovery accelerates, mood stabilizes. Months 3-6: Significant functional recovery. Months 6-12+: Continued brain remodeling, near-normal dopamine function. Full recovery: 1-2 years for most functions; some cognitive deficits may persist.',
    },
    philippines: {
      legality: 'Illegal under Republic Act No. 9165 (Comprehensive Dangerous Drugs Act of 2002). Possession, use, sale, manufacture, and cultivation are criminal offenses.',
      penalties: 'Possession of small quantity: 6 months + 4 years imprisonment + fine up to ₱500,000. Sale/trading: 12 years + 1 day to 20 years + fine up to ₱10,000,000. Importation/manufacturing: Life imprisonment to death + fine up to ₱50,000,000.',
      commonForm: 'Crystal ("shabu") - typically smoked in glass pipes or aluminum foil. Occasionally injected or taken orally. "Basura" refers to lower-quality or adulterated product.',
      streetPrice: '₱200-500 per small sachet (0.05-0.1g). ₱1,000-3,000 per gram. Price varies by region and purity. Metro Manila prices tend to be higher.',
    },
    harmReduction: [
      'Stay hydrated with electrolytes -- meth causes severe dehydration and sweating',
      'Never use alone -- have someone who can call for help in emergencies',
      'Avoid mixing with alcohol, other stimulants, or antidepressants (serotonin syndrome risk)',
      'Use the lowest effective dose and avoid binge patterns (redose >3x greatly increases neurotoxicity)',
      'Take antioxidants (Vitamin C, NAC) before and after use to reduce oxidative damage',
      'Eat before and after use -- meth suppresses appetite causing malnutrition',
      'Maintain sleep hygiene -- sleep deprivation dramatically increases neurotoxicity',
      'Monitor heart rate -- if resting HR exceeds 120bpm, seek medical attention',
      'Rotate veins and use clean equipment if injecting to prevent infection',
      'Have naloxone available -- while not an opioid, polydrug use is common',
    ],
    recoveryTips: [
      'Dopamine receptor recovery takes 6-12 months -- patience is essential, improvement is steady',
      'L-tyrosine + B-vitamins on an empty stomach each morning support dopamine synthesis',
      'Strict sleep schedule (bed/wake times) dramatically improves cognitive recovery and emotional regulation',
      'High-protein diet provides tyrosine and phenylalanine -- the raw materials for dopamine production',
      'Dental care is critical -- meth causes severe dental problems ("meth mouth"); see a dentist early in recovery',
    ],
    recoveryPhases: [
      {
        name: 'Acute Withdrawal -- The Crash',
        timeline: 'Days 0-14',
        neurochemicalState: 'Dopamine levels near zero. CRF hyperactive. Sleep severely disrupted -- minimal REM. Microglia activated (neuroinflammation). Gut permeability is high.',
        prioritySupplements: [
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'L-Glutamine', dosage: '5-10g' },
          { name: 'Probiotic Complex', dosage: '1-2 caps (10-50B CFU)' },
          { name: 'Prebiotic Inulin', dosage: '5-10g' },
          { name: 'Vitamin B6', dosage: '25-50mg' },
          { name: 'N-Acetyl Cysteine (NAC)', dosage: '600-1200mg' },
          { name: 'Buko Juice (Coconut Water)', dosage: '1-3 glasses' },
        ],
        dietaryFocus: [
          'High protein (chicken, fish, eggs)',
          'Bananas (potassium, tryptophan, B6)',
          'Malunggay (nutrient density, folate, iron)',
          'Frequent small meals',
          'Avoid sugar spikes',
        ],
        milestones: ['first_24h_clean', 'first_week_complete', 'sleeping_without_substance'],
      },
      {
        name: 'Early Recovery -- Rebuilding the Foundation',
        timeline: 'Days 14-60',
        neurochemicalState: 'Dopamine receptors beginning to upregulate slowly. HPA axis still dysregulated. Cortisol elevated. Anhedonia is primary symptom. Gut lining starting to repair.',
        prioritySupplements: [
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'L-Tyrosine', dosage: '500-1500mg' },
          { name: 'Omega-3 Fish Oil', dosage: '2000-4000mg EPA/DHA' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
          { name: 'L-Glutamine', dosage: '5-10g' },
          { name: 'Vitamin B6', dosage: '25-50mg' },
          { name: 'NAC', dosage: '600-1200mg' },
          { name: 'Tongkat Ali', dosage: '200-400mg' },
        ],
        dietaryFocus: [
          'Tyrosine-rich foods (eggs, chicken, dairy, almonds)',
          'Omega-3 sources (bangus, galunggong, sardines 3x/week)',
          'Complex carbohydrates (brown rice, camote)',
          'Atchara and fermented foods',
          'Hydration: 2-3L water + buko juice daily',
        ],
        milestones: ['two_weeks_clear', 'first_cravings_resisted', 'gut_healing_underway', 'sleep_improving'],
      },
      {
        name: 'Rebuilding -- Neuroplasticity Window',
        timeline: 'Months 2-6',
        neurochemicalState: 'Dopamine receptors significantly upregulating. BDNF production increasing. Neuroplasticity is high. HPA axis starting to normalize.',
        prioritySupplements: [
          { name: 'L-Tyrosine', dosage: '500-1500mg' },
          { name: 'Omega-3 Fish Oil', dosage: '2000-4000mg EPA/DHA' },
          { name: 'Creatine Monohydrate', dosage: '3-5g' },
          { name: 'Mucuna Pruriens', dosage: '250-500mg' },
          { name: 'Ashwagandha', dosage: '300-600mg' },
          { name: 'Turmeric/Curcumin', dosage: '500-1000mg' },
          { name: 'Tongkat Ali', dosage: '200-400mg' },
          { name: 'Vitamin B6', dosage: '25-50mg' },
        ],
        dietaryFocus: [
          'Brain-supportive foods: fatty fish, walnuts, blueberries',
          'High-quality protein at every meal',
          'Luyang dilaw (turmeric) daily',
          'Exercise to boost BDNF',
          'Reduce caffeine to 1 cup/day',
        ],
        milestones: ['two_months_milestone', 'anhedonia_improving', 'exercise_routine_established', 'first_moment_of_joy'],
      },
      {
        name: 'Maintenance -- Long-Term Recovery',
        timeline: 'Month 6+',
        neurochemicalState: 'Dopamine function approaching 70-80% of baseline. Neuroplasticity stabilizing. Gut-brain axis largely restored. Stress response normalized.',
        prioritySupplements: [
          { name: 'Omega-3 Fish Oil', dosage: '2000-4000mg EPA/DHA' },
          { name: 'Magnesium Glycinate', dosage: '300-400mg' },
          { name: 'Probiotic Complex', dosage: '1-2 caps' },
          { name: 'Vitamin B6', dosage: '25-50mg' },
          { name: 'Turmeric/Curcumin', dosage: '500-1000mg' },
          { name: 'Creatine Monohydrate', dosage: '3-5g' },
        ],
        dietaryFocus: [
          'Mediterranean-style diet adapted to PH',
          'Continue fermented foods (atchara, kimchi)',
          'Antioxidant-rich fruits: papaya, mango, guava',
          'Regular sleep schedule',
          'Social meals',
        ],
        milestones: ['six_months_clear', 'dopamine_rebuilding', 'career_or_study_focus', 'giving_back'],
      },
    ],
  };

export default methamphetamine;
